sudo: required

language: c

services:
  - docker

before_install:
  - docker build -f Dockerfile -t atgreen/moxielogic-repos .
  - mkdir MoxieLogic
  - docker run --rm -t -i -v `pwd`:/usr/local atgreen/moxielogic-repos /root/build.sh

script:
- 
