sudo: required

language: c

services:
  - docker

before_install:
  - docker pull atgreen/moxielogic-repos
  - docker run --rm -t -i -v `pwd`:/opt atgreen/moxielogic-repos ls -l /var/www/html
  - ls -l

script:
- 
