sudo: required

language: c

services:
  - docker

cache:
  directories:
    - $HOME/MoxieLogic
  before_cache:
    - $HOME/MoxieLogic

before_install:
  - if ! test -d $HOME/MoxieLogic; then mkdir $HOME/MoxieLogic; fi
  - pwd
  - ls -ld $HOME/MoxieLogic
  - ls -l $HOME/MoxieLogic
  - find $HOME/MoxieLogic -type f
  - docker build -f Dockerfile -t atgreen/moxielogic-repos .
  - docker run --rm -t -i -v $HOME:/usr/local atgreen/moxielogic-repos /root/build.sh
  - find $HOME/MoxieLogic -type f
  - if test -f $HOME/MoxieLogic/.done; then
      mv $HOME/MoxieLogic .
      docker build -f Dockerfile.repos -t atgreen/moxielogic-repos .;
    fi;

script:
  -

after_success:
  - if test -f MoxieLogic/.done; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push atgreen/moxielogic-repos;
    else
      ./.trigger;
    fi;

